"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSession } from "@/contexts/SessionContext";
import { useForm } from "@/contexts/FormContext";
import { ChatBubble } from "./ChatBubble";

export function ChatArea() {
  const { messages, addMessage, clearMessages } = useSession();
  const { prompt, selectedModel, parameters } = useForm();
  const [copySuccess, setCopySuccess] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async () => {
    if (!prompt.trim() || !selectedModel) return;
    
    setIsSubmitting(true);
    // Mock API call - in a real app, this would call an actual AI API
    await new Promise((resolve) => setTimeout(resolve, 1000));
    const mockResponse = `This is a mock response to your prompt: "${prompt}". In a real implementation, this would be generated by ${selectedModel} using the configured parameters (temperature: ${parameters.temperature}, max tokens: ${parameters.maxTokens}).`;
    
    addMessage({
      prompt,
      response: mockResponse,
      model: selectedModel,
      parameters: {
        temperature: parameters.temperature,
        maxTokens: parameters.maxTokens,
        topP: parameters.topP,
      },
    });
    setIsSubmitting(false);
  };

  const copyToClipboard = (text: string, messageId: string) => {
    navigator.clipboard.writeText(text);
    setCopySuccess(messageId);
    setTimeout(() => setCopySuccess(null), 2000);
  };

  const downloadJSON = (message: typeof messages[0]) => {
    const dataStr = JSON.stringify(message, null, 2);
    const dataBlob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `chat-message-${message.id}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-surface-light dark:bg-surface-dark rounded-xl p-6 border border-gray-200 dark:border-gray-700 shadow-sm"
    >
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-sm font-semibold text-text-primary-light dark:text-text-primary-dark">
          Chat / Output Area
        </h2>
        {messages.length > 0 && (
          <button
            onClick={clearMessages}
            className="px-4 py-2 text-sm bg-red-500 hover:bg-red-600 text-white rounded-lg focus-ring transition-colors"
            aria-label="Clear chat"
          >
            Clear Chat
          </button>
        )}
      </div>

      <div className="space-y-4 min-h-[400px] max-h-[600px] overflow-y-auto">
        <AnimatePresence>
          {messages.length === 0 ? (
            <div className="flex items-center justify-center h-full text-text-secondary-light dark:text-text-secondary-dark">
              <p>No messages yet. Submit a prompt to see responses here.</p>
            </div>
          ) : (
            messages.map((message) => (
              <motion.div
                key={message.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="space-y-3"
              >
                <ChatBubble
                  type="prompt"
                  content={message.prompt}
                  timestamp={message.timestamp}
                />
                <ChatBubble
                  type="response"
                  content={message.response}
                  timestamp={message.timestamp}
                />
                <div className="flex gap-2 ml-auto w-fit">
                  <button
                    onClick={() => copyToClipboard(message.response, message.id)}
                    className="px-3 py-1.5 text-xs bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-text-primary-light dark:text-text-primary-dark rounded-lg focus-ring transition-colors"
                    aria-label="Copy response"
                  >
                    {copySuccess === message.id ? "Copied!" : "Copy"}
                  </button>
                  <button
                    onClick={() => downloadJSON(message)}
                    className="px-3 py-1.5 text-xs bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 text-text-primary-light dark:text-text-primary-dark rounded-lg focus-ring transition-colors"
                    aria-label="Download JSON"
                  >
                    Download JSON
                  </button>
                </div>
              </motion.div>
            ))
          )}
        </AnimatePresence>
      </div>

      <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
        <button
          onClick={handleSubmit}
          disabled={!prompt.trim() || !selectedModel || isSubmitting}
          className="w-full px-6 py-3 bg-primary-500 hover:bg-primary-600 text-white rounded-lg font-medium focus-ring transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          aria-label="Submit prompt"
        >
          {isSubmitting ? "Submitting..." : "Submit Prompt"}
        </button>
      </div>
    </motion.div>
  );
}

